os:
- linux
language: java
jdk:
- oraclejdk8
env:
- NODE_VERSION=0.12
- nvm use $NODE_VERSION
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    - lib32z1
before_install:
- openssl aes-256-cbc -K $encrypted_133299118ef1_key -iv $encrypted_133299118ef1_iv -in deploy_rsa.enc -out deploy_rsa -d
- echo before_install
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- export LANG=en_US.UTF-8
- ls -la web/
- cd web
- npm install
- npm run build:prod
- ls -la
- cd ..
install:
- echo install
before_script:
- echo before_script
- echo $JAVA_HOME
- java -version
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- echo script
after_script:
- echo after_script
- rm -rf *
