os:
- linux
language: java
jdk:
- oraclejdk8
node_js:
- node
- '7'
env:
- NODE_VERSION=8.1.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    - lib32z1
before_install:
- echo before_install
- openssl aes-256-cbc -K $encrypted_133299118ef1_key -iv $encrypted_133299118ef1_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- nvm install $NODE_VERSION
- export LANG=en_US.UTF-8
- ls -la web/
- ls -la web/parse_cloud/
- scp -r -o StrictHostKeyChecking=no -i deploy_rsa web/parse_cloud/* root@162.243.118.87:/root/202_app/cloud/
- cd web
- node -v
- npm -v
- rm -rf package-lock.json
- npm install
- npm run build:prod
- ls -la
- cd ..
install:
- echo install
- scp -Cr -o StrictHostKeyChecking=no -i $awsKey web/dist/* ec2-user@ec2-52-42-240-155.us-west-2.compute.amazonaws.com:/var/www/html/
- scp -r -o StrictHostKeyChecking=no -i deploy_rsa web/dist/* root@162.243.118.87:/var/www/202.tanzeelrana.me/www/
before_script:
- echo before_script
- echo $JAVA_HOME
- java -version
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
- echo script
after_script:
- echo after_script
- rm -rf *
